export const demoUser = {
  id: 'demo-admin-001',
  email: 'admin@cabana.demo',
  role: 'admin',
  user_metadata: {
    full_name: 'Alex Morgan',
  },
};

export const demoTalent = [
  {
    id: 'talent-001',
    first_name: 'Sophia',
    last_name: 'Rivera',
    stage_name: 'Sophie R.',
    email: 'sophie@talent.demo',
    status: 'active',
    verification_status: 'verified',
    bio: 'NYC-based nightlife host and brand ambassador specializing in luxury hospitality and high-end events.',
    instagram_handle: '@sophierivera',
    follower_count: 125000,
    category: 'Nightlife',
    location: 'New York, NY',
    rate_card: { hourly: 500, event: 2500, campaign: 8000 },
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'talent-002',
    first_name: 'Marcus',
    last_name: 'Chen',
    stage_name: 'MC',
    email: 'marcus@talent.demo',
    status: 'active',
    verification_status: 'verified',
    bio: 'LA-based promotional model and brand representative with focus on beverage and lifestyle campaigns.',
    instagram_handle: '@marcuschen',
    follower_count: 89000,
    category: 'Brand Campaigns',
    location: 'Los Angeles, CA',
    rate_card: { hourly: 400, event: 2000, campaign: 6500 },
    created_at: '2024-02-20T14:30:00Z',
  },
  {
    id: 'talent-003',
    first_name: 'Isabella',
    last_name: 'Martinez',
    stage_name: 'Bella M',
    email: 'bella@talent.demo',
    status: 'active',
    verification_status: 'verified',
    bio: 'Miami nightlife specialist and corporate event host. Elite hospitality professional.',
    instagram_handle: '@bellamartinez',
    follower_count: 210000,
    category: 'Nightlife',
    location: 'Miami, FL',
    rate_card: { hourly: 600, event: 3000, campaign: 10000 },
    created_at: '2024-01-10T09:15:00Z',
  },
  {
    id: 'talent-004',
    first_name: 'Jordan',
    last_name: 'Taylor',
    stage_name: 'JT',
    email: 'jordan@talent.demo',
    status: 'pending',
    verification_status: 'pending_background',
    bio: 'Las Vegas event host and promotional talent. Specializes in casino events and high-stakes entertainment.',
    instagram_handle: '@jordantaylor',
    follower_count: 45000,
    category: 'Events',
    location: 'Las Vegas, NV',
    rate_card: { hourly: 350, event: 1800, campaign: 5000 },
    created_at: '2024-11-15T16:20:00Z',
  },
  {
    id: 'talent-005',
    first_name: 'Amara',
    last_name: 'Johnson',
    stage_name: 'Amara J',
    email: 'amara@talent.demo',
    status: 'active',
    verification_status: 'verified',
    bio: 'Chicago-based brand ambassador and lifestyle influencer. Corporate events and product launches.',
    instagram_handle: '@amarajohnson',
    follower_count: 156000,
    category: 'Brand Campaigns',
    location: 'Chicago, IL',
    rate_card: { hourly: 450, event: 2200, campaign: 7500 },
    created_at: '2024-03-05T11:00:00Z',
  },
  {
    id: 'talent-006',
    first_name: 'Devon',
    last_name: 'Williams',
    stage_name: 'Dev',
    email: 'devon@talent.demo',
    status: 'active',
    verification_status: 'verified',
    bio: 'Atlanta nightlife curator and VIP host. Expertise in bottle service and exclusive venue experiences.',
    instagram_handle: '@devonwilliams',
    follower_count: 98000,
    category: 'Nightlife',
    location: 'Atlanta, GA',
    rate_card: { hourly: 400, event: 2100, campaign: 6000 },
    created_at: '2024-02-28T13:45:00Z',
  },
  {
    id: 'talent-007',
    first_name: 'Sienna',
    last_name: 'Brooks',
    stage_name: 'Sienna',
    email: 'sienna@talent.demo',
    status: 'active',
    verification_status: 'verified',
    bio: 'San Francisco tech event specialist and corporate hospitality professional.',
    instagram_handle: '@siennabrooks',
    follower_count: 67000,
    category: 'Events',
    location: 'San Francisco, CA',
    rate_card: { hourly: 425, event: 2300, campaign: 7000 },
    created_at: '2024-04-12T10:30:00Z',
  },
  {
    id: 'talent-008',
    first_name: 'Kai',
    last_name: 'Anderson',
    stage_name: 'Kai A',
    email: 'kai@talent.demo',
    status: 'pending',
    verification_status: 'pending_id',
    bio: 'Dallas-based promotional model and brand representative. Focus on automotive and luxury brands.',
    instagram_handle: '@kaianderson',
    follower_count: 34000,
    category: 'Brand Campaigns',
    location: 'Dallas, TX',
    rate_card: { hourly: 300, event: 1500, campaign: 4500 },
    created_at: '2024-11-20T09:00:00Z',
  },
];

export const demoClients = [
  {
    id: 'client-001',
    name: 'LUX Nightlife Group',
    industry: 'Hospitality',
    contact_email: 'bookings@luxnightlife.demo',
    status: 'active',
    tier: 'platinum',
    created_at: '2023-06-15T11:00:00Z',
  },
  {
    id: 'client-002',
    name: 'Prestige Brands Inc',
    industry: 'Marketing',
    contact_email: 'talent@prestigebrands.demo',
    status: 'active',
    tier: 'gold',
    created_at: '2023-08-20T16:20:00Z',
  },
  {
    id: 'client-003',
    name: 'Elite Events Miami',
    industry: 'Events',
    contact_email: 'coordination@eliteevents.demo',
    status: 'active',
    tier: 'platinum',
    created_at: '2023-05-10T14:45:00Z',
  },
  {
    id: 'client-004',
    name: 'Velocity Casino Group',
    industry: 'Gaming',
    contact_email: 'hr@velocitycasino.demo',
    status: 'active',
    tier: 'gold',
    created_at: '2024-01-22T10:00:00Z',
  },
  {
    id: 'client-005',
    name: 'Urban Spirits Co',
    industry: 'Beverage',
    contact_email: 'marketing@urbanspirits.demo',
    status: 'active',
    tier: 'silver',
    created_at: '2024-09-15T12:30:00Z',
  },
];

export const demoBookings = [
  {
    id: 'booking-001',
    talent_id: 'talent-001',
    talent_name: 'Sophia Rivera',
    client_id: 'client-001',
    client_name: 'LUX Nightlife Group',
    status: 'confirmed',
    project_name: 'NYE VIP Host - Manhattan',
    amount: 3500,
    deposit_paid: true,
    start_date: '2024-12-31T22:00:00Z',
    end_date: '2025-01-01T04:00:00Z',
    location: 'New York, NY',
    created_at: '2024-11-15T10:00:00Z',
  },
  {
    id: 'booking-002',
    talent_id: 'talent-003',
    talent_name: 'Isabella Martinez',
    client_id: 'client-003',
    client_name: 'Elite Events Miami',
    status: 'confirmed',
    project_name: 'Art Basel VIP Hospitality',
    amount: 4500,
    deposit_paid: true,
    start_date: '2024-12-06T20:00:00Z',
    end_date: '2024-12-07T02:00:00Z',
    location: 'Miami, FL',
    created_at: '2024-10-20T14:00:00Z',
  },
  {
    id: 'booking-003',
    talent_id: 'talent-002',
    talent_name: 'Marcus Chen',
    client_id: 'client-005',
    client_name: 'Urban Spirits Co',
    status: 'requested',
    project_name: 'Winter Product Launch LA',
    amount: 6500,
    deposit_paid: false,
    start_date: '2025-01-15T18:00:00Z',
    end_date: '2025-01-15T23:00:00Z',
    location: 'Los Angeles, CA',
    created_at: '2024-11-28T09:30:00Z',
  },
  {
    id: 'booking-004',
    talent_id: 'talent-005',
    talent_name: 'Amara Johnson',
    client_id: 'client-002',
    client_name: 'Prestige Brands Inc',
    status: 'pending_review',
    project_name: 'Q1 Brand Ambassador Campaign',
    amount: 7500,
    deposit_paid: false,
    start_date: '2025-02-01T09:00:00Z',
    end_date: '2025-02-28T17:00:00Z',
    location: 'Chicago, IL',
    created_at: '2024-11-25T11:00:00Z',
  },
  {
    id: 'booking-005',
    talent_id: 'talent-006',
    talent_name: 'Devon Williams',
    client_id: 'client-001',
    client_name: 'LUX Nightlife Group',
    status: 'completed',
    project_name: 'Thanksgiving Weekend VIP Host',
    amount: 2800,
    deposit_paid: true,
    start_date: '2024-11-29T22:00:00Z',
    end_date: '2024-11-30T04:00:00Z',
    location: 'Atlanta, GA',
    created_at: '2024-10-15T16:00:00Z',
  },
  {
    id: 'booking-006',
    talent_id: 'talent-007',
    talent_name: 'Sienna Brooks',
    client_id: 'client-002',
    client_name: 'Prestige Brands Inc',
    status: 'confirmed',
    project_name: 'Tech Summit Hostess Services',
    amount: 2300,
    deposit_paid: true,
    start_date: '2024-12-10T08:00:00Z',
    end_date: '2024-12-10T18:00:00Z',
    location: 'San Francisco, CA',
    created_at: '2024-11-01T13:00:00Z',
  },
  {
    id: 'booking-007',
    talent_id: 'talent-004',
    talent_name: 'Jordan Taylor',
    client_id: 'client-004',
    client_name: 'Velocity Casino Group',
    status: 'pending_review',
    project_name: 'High Roller Weekend Host',
    amount: 1800,
    deposit_paid: false,
    start_date: '2024-12-20T20:00:00Z',
    end_date: '2024-12-21T03:00:00Z',
    location: 'Las Vegas, NV',
    created_at: '2024-11-22T10:00:00Z',
  },
  {
    id: 'booking-008',
    talent_id: 'talent-001',
    talent_name: 'Sophia Rivera',
    client_id: 'client-002',
    client_name: 'Prestige Brands Inc',
    status: 'completed',
    project_name: 'Fall Fashion Week Hospitality',
    amount: 5000,
    deposit_paid: true,
    start_date: '2024-09-15T18:00:00Z',
    end_date: '2024-09-20T22:00:00Z',
    location: 'New York, NY',
    created_at: '2024-08-10T12:00:00Z',
  },
  {
    id: 'booking-009',
    talent_id: 'talent-003',
    talent_name: 'Isabella Martinez',
    client_id: 'client-001',
    client_name: 'LUX Nightlife Group',
    status: 'cancelled',
    project_name: 'Memorial Day Weekend VIP',
    amount: 3000,
    deposit_paid: false,
    start_date: '2024-05-25T22:00:00Z',
    end_date: '2024-05-26T04:00:00Z',
    location: 'Miami, FL',
    created_at: '2024-04-20T09:00:00Z',
  },
  {
    id: 'booking-010',
    talent_id: 'talent-005',
    talent_name: 'Amara Johnson',
    client_id: 'client-003',
    client_name: 'Elite Events Miami',
    status: 'confirmed',
    project_name: 'Corporate Holiday Party Host',
    amount: 2200,
    deposit_paid: true,
    start_date: '2024-12-15T19:00:00Z',
    end_date: '2024-12-15T23:00:00Z',
    location: 'Chicago, IL',
    created_at: '2024-10-30T15:00:00Z',
  },
  {
    id: 'booking-011',
    talent_id: 'talent-006',
    talent_name: 'Devon Williams',
    client_id: 'client-005',
    client_name: 'Urban Spirits Co',
    status: 'requested',
    project_name: 'Spring Cocktail Launch Atlanta',
    amount: 2100,
    deposit_paid: false,
    start_date: '2025-03-05T19:00:00Z',
    end_date: '2025-03-05T23:00:00Z',
    location: 'Atlanta, GA',
    created_at: '2024-11-27T14:00:00Z',
  },
  {
    id: 'booking-012',
    talent_id: 'talent-002',
    talent_name: 'Marcus Chen',
    client_id: 'client-002',
    client_name: 'Prestige Brands Inc',
    status: 'completed',
    project_name: 'Summer Brand Activation LA',
    amount: 8000,
    deposit_paid: true,
    start_date: '2024-07-01T10:00:00Z',
    end_date: '2024-07-31T18:00:00Z',
    location: 'Los Angeles, CA',
    created_at: '2024-05-15T11:00:00Z',
  },
];

export const demoStats = {
  total_revenue: 287400,
  active_bookings: 5,
  pending_requests: 3,
  total_talent: 8,
  verified_talent: 6,
  this_month_revenue: 38200,
  avg_booking_value: 3420,
};
