#!/usr/bin/env bash
set -euo pipefail

# Vercel Environment Variable Sync Script
# Run this after deploying to add new environment variables

echo "🔧 Syncing Environment Variables to Vercel..."
echo ""
echo "📋 New variables to add (from PR2-PR4):"
echo ""
echo "  Email Provider (Required for invites):"
echo "  - RESEND_API_KEY"
echo "  - MAIL_FROM"
echo ""
echo "  Webhook Secrets (Optional - configure when vendors active):"
echo "  - VERIFF_WEBHOOK_SECRET (or ONFIDO_WEBHOOK_SECRET)"
echo "  - CHECKR_WEBHOOK_SECRET (or CERTN_WEBHOOK_SECRET)"
echo "  - DOCUSIGN_CONNECT_KEY"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Manual Steps (run these commands):"
echo ""
echo "  # Email Provider"
echo "  vercel env add RESEND_API_KEY production"
echo "  vercel env add MAIL_FROM production"
echo ""
echo "  # Webhook Secrets (add when vendors configured)"
echo "  vercel env add VERIFF_WEBHOOK_SECRET production"
echo "  vercel env add CHECKR_WEBHOOK_SECRET production"
echo "  vercel env add DOCUSIGN_CONNECT_KEY production"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ After adding variables, verify with:"
echo "   vercel env pull .env.vercel.local"
echo ""
echo "⚠️  Existing variables (should already be set):"
echo "   - NEXT_PUBLIC_SUPABASE_URL"
echo "   - NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   - SUPABASE_SERVICE_ROLE_KEY"
echo "   - ADMIN_EMAILS"
echo "   - STRIPE_SECRET_KEY"
echo "   - STRIPE_WEBHOOK_SECRET"
echo "   - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
echo ""

